### ISSUE TITLE
No module named 'PyQt5'

### ISSUE THREAD

**Issue by dzyla** [charbj/wiggle#1]
Hi!

Thanks for the tool! I followed your tutorial; however, it has problems finding PyQt5. I tried to install it together with the rest of the packages but had no luck:

`./../usr/lib/ucsf-chimerax/bin/python3.9 -m pip install cupy-cuda102 mrcfile phate umap-learn pyqtgraph scikit-image sklearn torch pyqt5`

chimeraX: version 1.4 (2022-06-03)

The error happens when I try to start the GUI of wiggle:

```
[ui tool show](help:user/commands/ui.html#tool-show) WiggleTraceback (most recent call last):
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 559, in start_tool
    ti = api._api_caller.start_tool(api, session, self, tool_info)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/__init__.py", line 1325, in start_tool
    return cls._get_func(api, "start_tool")(session, bi, ti)
  File "/home/dzyla/.local/share/ChimeraX/1.4/site-packages/chimerax/wiggle/__init__.py", line 29, in start_tool
    from . import tool
  File "/home/dzyla/.local/share/ChimeraX/1.4/site-packages/chimerax/wiggle/tool.py", line 15, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/ui/gui.py", line 1685, in <lambda>
    run(ses, "ui tool show %s" % StringArg.unparse(tool_name)))
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/commands/run.py", line 38, in run
    results = command.run(text, log=log, return_json=return_json)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/commands/cli.py", line 2897, in run
    result = ci.function(session, **kw_args)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/ui/cmd.py", line 219, in ui_tool_show
    bi.start_tool(session, name)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 564, in start_tool
    raise ToolshedError(
chimerax.core.toolshed.ToolshedError: start_tool() failed for tool Wiggle in bundle wiggle:
No module named 'PyQt5'

chimerax.core.toolshed.ToolshedError: start_tool() failed for tool Wiggle in bundle wiggle:
No module named 'PyQt5'

File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 564, in start_tool
raise ToolshedError(

See log for complete Python traceback.
```

If you could share how it worked for you, that would be great! 

Thanks,
Dawid

**Comment by charbj** [comment]
Hi Dawid. 

Thanks for trying out Wiggle.

This is a ChimeraX 1.4 problem which now uses PySide6 (or PyQT6). I will need to make some modifications to Wiggle to bring it up to speed with version 1.4. On my to-do list! 

Currently, you will have to use ChimeraX 1.3 which still uses PyQt5.

Hope that helps,
Charles

**Comment by dzyla** [comment]
Thanks for the reply! Yeah, it makes a lot of sense now. The problem is that on Ubuntu 22.04, ChimeraX version 1.3 does not work (windows are not properly rendered).

I will wait for the update, and good luck!

**Comment by charbj** [comment]
Okay - this seems like an easier fix than I anticipated. The `wiggle_0.2.2X1.4` branch should work, I have tested on Ubuntu 22.04 and ChimeraX 1.4. Although on my laptop the UI is cramped, but this is mostly aesthetic.

try:
`git pull`
`git checkout wiggle_0.2.2X1.4`

Then rebuild in ChimeraX with
`devel build /path/to/wiggle/; devel install /path/to/wiggle/; ui tool show wiggle`

https://github.com/charbj/wiggle/tree/wiggle_0.2.2X1.4

**Comment by dzyla** [comment]
Wow, that was fast! Thanks!

I followed the instructions, and the installation finished properly, but this time it showed a different error:

```
chimerax.core.toolshed.ToolshedError: start_tool() failed for tool Wiggle in bundle wiggle:
trying to start unknown tool: Wiggle

File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 564, in start_tool
raise ToolshedError(

See log for complete Python traceback.
```

and the python output:

```
[ui tool show](help:user/commands/ui.html#tool-show) wiggleTraceback (most recent call last):
  File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 559, in start_tool
    ti = api._api_caller.start_tool(api, session, self, tool_info)
  File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/core/toolshed/__init__.py", line 1325, in start_tool
    return cls._get_func(api, "start_tool")(session, bi, ti)
  File "/home/dzyla/.local/share/ChimeraX/1.4/site-packages/chimerax/wiggle/__init__.py", line 31, in start_tool
    raise ValueError("trying to start unknown tool: %s" % ti.name)
ValueError: trying to start unknown tool: Wiggle

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/cmd_line/tool.py", line 319, in execute
    cmd.run(cmd_text)
  File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/core/commands/cli.py", line 2897, in run
    result = ci.function(session, **kw_args)
  File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/ui/cmd.py", line 219, in ui_tool_show
    bi.start_tool(session, name)
  File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 564, in start_tool
    raise ToolshedError(
chimerax.core.toolshed.ToolshedError: start_tool() failed for tool Wiggle in bundle wiggle:
trying to start unknown tool: Wiggle

chimerax.core.toolshed.ToolshedError: start_tool() failed for tool Wiggle in bundle wiggle:
trying to start unknown tool: Wiggle

File "/usr/lib/ucsf-chimerax-daily/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 564, in start_tool
raise ToolshedError(
```

Seems like that after the installation the wiggle tool is not recognized anymore by ChimeraX

**Comment by charbj** [comment]
Cool, we have progress! This is a minor change that wasn't pushed properly to the repository. That's my bad.

Can you please update with `git pull` and try again. Obviously make sure you're in the wiggle_0.2.2X1.4 branch.

For some reason, I found that I had to close chimera and run `devel clean /path/to/wiggle/` to purge, before it would build/install with the new changes.

Thanks for your patience! 
Best,
Charles

**Comment by dzyla** [comment]
So I have done as you suggested, and there is indeed progress! Another package that should be installed (confirmed manually) is not recognized by Chimerax. This time it might be an issue on my side (didn't do a clean ChimeraX reinstall). Error here:

```
[ui tool show]
(help:user/commands/ui.html#tool-show) wiggleTraceback (most recent call last):
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 559, in start_tool
    ti = api._api_caller.start_tool(api, session, self, tool_info)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/__init__.py", line 1325, in start_tool
    return cls._get_func(api, "start_tool")(session, bi, ti)
  File "/home/dzyla/.local/share/ChimeraX/1.4/site-packages/chimerax/wiggle/__init__.py", line 29, in start_tool
    from . import tool
  File "/home/dzyla/.local/share/ChimeraX/1.4/site-packages/chimerax/wiggle/tool.py", line 16, in <module>
    import pyqtgraph as pg
ModuleNotFoundError: No module named 'pyqtgraph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/cmd_line/tool.py", line 319, in execute
    cmd.run(cmd_text)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/commands/cli.py", line 2897, in run
    result = ci.function(session, **kw_args)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/ui/cmd.py", line 219, in ui_tool_show
    bi.start_tool(session, name)
  File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 564, in start_tool
    raise ToolshedError(
chimerax.core.toolshed.ToolshedError: start_tool() failed for tool wiggle in bundle wiggle:
No module named 'pyqtgraph'

chimerax.core.toolshed.ToolshedError: start_tool() failed for tool wiggle in bundle wiggle:
No module named 'pyqtgraph'

File "/usr/lib/ucsf-chimerax/lib/python3.9/site-packages/chimerax/core/toolshed/info.py", line 564, in start_tool
raise ToolshedError(

See log for complete Python traceback.
```

**Comment by charbj** [comment]
Hi Dawid.

This is quite odd - I can't reproduce this error on my system. When you say "confirmed manually", I'm assuming you mean that in an interactive shell ChimeraX-python is able to import pyqtgraph, but for some reason chimeraX fails to recognise this module? 

Obviously if the ChimeraX-python is unable to find that module in an interactive shell, it is likely just not installed properly. That should be a simple fix i.e. `ChimeraX-python3.9 -m pip install pyqtgraph` - I'm guessing you have done this, but for others I mention it. 

One thing you could try is to add pyqtgraph as a dependency in the `bundle_info.xml` file, for example below:

```
  <Dependencies>
    <Dependency name="ChimeraX-Core" version="~=1.1"/>
    <Dependency name="ChimeraX-UI" version="~=1.0"/>
    <Dependency name="pyqtgraph" version="~=0.12.4"/>
  </Dependencies>
```

Then re-perform clean/build/install commands in ChimeraX.

I really appreciate your perseverance! 

Best,
Charles
